name: Release workflow

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest

    environment: npm

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          #GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GIT_AUTHOR_NAME: "Alex Gherghisan"
          #GIT_AUTHOR_EMAIL: "alexghr@users.noreply.github.com"
          #GIT_COMMITTER_NAME: "Alex Gherghisan"
          #GIT_COMMITTER_EMAIL: "alexghr@users.noreply.github.com"
