name: Release workflow

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest

    environment: npm

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
